### ISSUE TITLE
Child_HWLink on hardware

### ISSUE THREAD

**Issue by Jeville** [hylian-modding/Z64-CustomPlayerModels#88]
![hyrulew](https://user-images.githubusercontent.com/40967133/185514202-083d5d60-10b8-49ae-a5dc-29810dae1fbb.png)

Keaton mask is maybe the only flaw.

**Comment by denoflionsx** [comment]
This repository is for Oot Online/MM Online and as such we do not test on
hardware. I'll pass this along to the actual modeler but it's up them if
they care to try and do anything about it.
