### ISSUE TITLE
Combined_KristinaV2 child model is too large

### ISSUE THREAD

**Issue by Jeville** [hylian-modding/Z64-CustomPlayerModels#89]
![kris](https://user-images.githubusercontent.com/40967133/185516016-e6691222-2429-4c59-b4a4-3d561996e538.png)

Adult is perfect.

**Comment by denoflionsx** [comment]
This is not a bug. Models designed for Oot Online can be larger than
original hardware models.

**Comment by alkaris2** [comment]
How is this not a bug? I have this exact issue with some other models being too big for randomizer generation, and this GitHub repository appears to be the only place to get these model files from.

**Comment by denoflionsx** [comment]
This repository is for OotOnline which does not have size limits on zobjs.
Rando has the vanilla size limit due to how they chose to implement custom
models.

It isn't a bug. If rando players not using OotOnline want bigger models the
implementation rando uses has to change to allow it.
